name: Build .sln Solution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Adjust based on your project

    - name: Build Solution
      run: dotnet build BWC4WIFE/TweakUIX/src/TUIX.sln --configuration Release
